Feature
HtetNaing0814/Portfolio pull request #1
Opened 2022-05-25 14:00 UTC by HtetNaing0814

2022-05-25 16:08 UTC, tufoinnkuo10 requested changes
Hi @HtetNaing0814 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not have linter checks. you can see how to setup linters [here](https://github.com/microverseinc/linters-config/tree/master/html-css)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-26 01:50 UTC, HtetNaing0814 commented
Thank u so much. I'll do so. But I'd like to know how do I tag you?

On Wed, May 25, 2022, 10:38 PM TufoinNkuo ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @HtetNaing0814 <https://github.com/HtetNaing0814> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a project that does not have linter checks. you can see
> how to setup linters here
> <https://github.com/microverseinc/linters-config/tree/master/html-css>
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HtetNaing0814/Portfolio/pull/1#pullrequestreview-985105689>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASORG4ALJYXNVWI23Y6JCXDVLZF7PANCNFSM5W5HV22Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-26 07:22 UTC, sja-thedude reviewed
## Invalid Code Review Request  ❌

Hi @HtetNaing0814, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have linters setup correctly, doesn't have a pull request description [here](https://github.com/HtetNaing0814/Portfolio/pull/1#issue-1248146496) and make sure to add a descriptive pull request title.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-26 07:57 UTC, sja-thedude reviewed
## Invalid Code Review Request  ❌

Hi @HtetNaing0814, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have linters setup correctly which means i cant see the green check marks, doesn't have a pull request description [here](https://github.com/HtetNaing0814/Portfolio/pull/1#issue-1248146496) which means it is empty and make sure to add a descriptive pull request title like your project name "Portfolio: Setup".

## If you are not able to understand kindly tag me as shown below.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-26 09:49 UTC, HtetNaing0814 commented
I do really have no idea what you are talking about. I thought I added
linters before submitting again. Furthermore, Do I need to make new pull
request?

On Thu, May 26, 2022, 2:27 PM Syeda Juveria Afreen ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> Invalid Code Review Request ❌
>
> Hi @HtetNaing0814 <https://github.com/HtetNaing0814>,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
>
> You have submitted a project, that doesn't have linters setup correctly
> which means i cant see the green check marks, doesn't have a pull request
> description here
> <https://github.com/HtetNaing0814/Portfolio/pull/1#issue-1248146496>
> which means it is empty and make sure to add a descriptive pull request
> title like your project name "Portfolio: Setup".
> If you are not able to understand kindly tag me as shown below.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me ***@***.*** <https://github.com/sja-thedude>]
> in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HtetNaing0814/Portfolio/pull/1#pullrequestreview-985860889>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASORG4BTBQMKUV7CKAATXNLVL4VHNANCNFSM5W5HV22Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-26 10:14 UTC, HtetNaing0814 commented
Somebody help me please.


On Thu, May 26, 2022 at 4:18 PM Htet Naing ***@***.***> wrote:

> I do really have no idea what you are talking about. I thought I added
> linters before submitting again. Furthermore, Do I need to make new pull
> request?
>
> On Thu, May 26, 2022, 2:27 PM Syeda Juveria Afreen <
> ***@***.***> wrote:
>
>> ***@***.**** commented on this pull request.
>> Invalid Code Review Request ❌
>>
>> Hi @HtetNaing0814 <https://github.com/HtetNaing0814>,
>>
>> While you made a great effort in this project, unfortunately, I cannot
>> proceed to review your code.
>>
>> You have submitted a project, that doesn't have linters setup correctly
>> which means i cant see the green check marks, doesn't have a pull request
>> description here
>> <https://github.com/HtetNaing0814/Portfolio/pull/1#issue-1248146496>
>> which means it is empty and make sure to add a descriptive pull request
>> title like your project name "Portfolio: Setup".
>> If you are not able to understand kindly tag me as shown below.
>>
>> Your Code Review Request will be marked as invalid in your Dashboard, so
>> please submit a new one once you are ready 🙏
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me ***@***.*** <https://github.com/sja-thedude>]
>> in your question so I can receive the notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *Invalid Code Review Request does not count into the code reviews limit.*
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/HtetNaing0814/Portfolio/pull/1#pullrequestreview-985860889>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ASORG4BTBQMKUV7CKAATXNLVL4VHNANCNFSM5W5HV22Q>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-05-26 12:20 UTC, sja-thedude commented
> I do really have no idea what you are talking about. I thought I added linters before submitting again.

@HtetNaing0814 You have to correctly set up linters, which means i can't see the green check marks. Also, your PR doesn't have a pull request description https://github.com/HtetNaing0814/Portfolio/pull/1#issue-1248146496 which means it is empty, kindly add a description of what changes you made in the project. Also, make sure to add a descriptive pull request title like your project name is "Feature", kindly replace it with "Portfolio: Setup".

2022-05-26 13:06 UTC, arslanbisharat requested changes
Hi @HtetNaing0814, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlight

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 13:06 UTC, arslanbisharat commented on portfolio.html
> +        </div> -->
- [ ] Remove the commented code from your project as it makes code hard to read.

2022-05-26 13:06 UTC, arslanbisharat commented on portfolio.html
> +            </div> -->
- [ ] Remove the commented code from your project as it makes code hard to read.

2022-05-26 13:06 UTC, arslanbisharat commented on portfolio.html
> +        <div class="toolbar">
- [ ] The container of the section should be a header tag

2022-05-26 13:06 UTC, arslanbisharat commented on portfolio.html
> +            <img class="menu" src="./assets/menu.svg" alt="menu">
- [ ] 1. The hamburger button should be on the right and has a `nav` tag

2022-05-26 13:06 UTC, arslanbisharat commented on portfolio.html
> +        </div>
- [ ] The content should be aligned with flexbox

2022-05-26 13:06 UTC, arslanbisharat commented on portfolio.html
> +        </div>
- [ ] The container of the section should be a `section` tag

2022-05-26 13:06 UTC, arslanbisharat commented on portfolio.html
> +        <p class="intro primary-color">Hey there. I’m Rex.</p>
- [ ]  The main title (e.g., "I'm Marianne ...") is a `h1` tag

2022-05-26 13:06 UTC, arslanbisharat commented on portfolio.html
> +        <p class="intro secondary-color">I am a full stack developer.</p>
- [ ] The subtitle (if existing) uses a header tag `hx (examples: <h1>,<h2>,<h3>, etc...)`

2022-05-26 13:06 UTC, arslanbisharat commented on README.md
> +1. Clone this repository or download the zip folder:
- [ ] [OPTIONAL] Please add a live link of your project

2022-05-26 16:16 UTC, ishimwezachee approved these changes
Hi @HtetNaing0814 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

- [OPTIONAL ] I am sorry for these was not mentioned by previous reviewers but its very important for your project. You should have Sementic Element in your project. That means you should have some thing like 
![image](https://user-images.githubusercontent.com/43877689/170529681-9948f31e-0b34-414d-be6d-2e2aaee062a5.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 01:18 UTC, merged